import { useState } from 'react';
import { menuPermissions } from '../../data/navigation.js';
import Button from '../../components/Button.jsx';

const initialUsers = [{ name: '관리자', email: 'admin@example.com', role: 'admin' }, { name: '운영자', email: 'operator@example.com', role: 'operator' }, { name: '조회자', email: 'viewer@example.com', role: 'viewer' }];
const initialRules = { admin: { prompt: ['read', 'manage'], result: ['read', 'manage'], admin: ['read', 'manage'] }, operator: { prompt: ['read', 'manage'], result: ['read', 'manage'], admin: ['read'] }, viewer: { prompt: ['read'], result: ['read'], admin: [] } };

export default function AdminPage({ canManage }) {
  const [users, setUsers] = useState(initialUsers); const [rules, setRules] = useState(initialRules); const [saved, setSaved] = useState(false);
  const toggle = (role, menu, action) => setRules({ ...rules, [role]: { ...rules[role], [menu]: rules[role][menu].includes(action) ? rules[role][menu].filter((item) => item !== action) : [...rules[role][menu], action] } });
  return <section className="admin-view"><div className="toolbar"><div><h1>관리자 모드</h1><p className="muted">사용자와 메뉴 접근 권한을 관리합니다.</p></div><Button variant="primary" disabled={!canManage} onClick={() => setSaved(true)}>권한 저장</Button></div>{saved && <p className="success" role="status">저장되었습니다. 실제 저장은 Node API 연결 후 적용됩니다.</p>}<section className="admin-panel"><h2>사용자 관리</h2><table><thead><tr><th>이름</th><th>이메일</th><th>역할</th><th>상태</th></tr></thead><tbody>{users.map((user) => <tr key={user.email}><td>{user.name}</td><td>{user.email}</td><td><select disabled={!canManage} value={user.role} onChange={(e) => setUsers(users.map((item) => item.email === user.email ? { ...item, role: e.target.value } : item))}><option value="admin">admin</option><option value="operator">operator</option><option value="viewer">viewer</option></select></td><td><span className="badge">활성</span></td></tr>)}</tbody></table></section><section className="admin-panel"><h2>역할별 메뉴 권한</h2><table><thead><tr><th>역할</th>{menuPermissions.map((menu) => <th key={menu.id}>{menu.label}</th>)}</tr></thead><tbody>{Object.keys(rules).map((role) => <tr key={role}><th>{role}</th>{menuPermissions.map((menu) => <td key={menu.id}><label className="permission"><input disabled={!canManage} type="checkbox" checked={rules[role][menu.id].includes('read')} onChange={() => toggle(role, menu.id, 'read')} /> 조회</label><label className="permission"><input disabled={!canManage} type="checkbox" checked={rules[role][menu.id].includes('manage')} onChange={() => toggle(role, menu.id, 'manage')} /> 관리</label></td>)}</tr>)}</tbody></table></section></section>;
}
