const state = { template: 'executive', format: 'docx', rows: [
  ['13:02', '결제 API 응답 지연 및 간헐적 타임아웃 발생'],
  ['13:10', '오류율 12%로 증가, DB 커넥션 사용량 95% 확인'],
  ['13:22', '원인 파악: 배치 작업으로 인한 커넥션 풀 고갈'],
  ['13:40', '커넥션 풀 상향 및 보조 리전 트래픽 우회 적용'],
  ['14:35', '오류율 0.1% 이하로 안정화, 모니터링 전환']
]};

const $ = (id) => document.getElementById(id);
function renderRows() { $('timelineEditor').innerHTML = `<div class="timeline-head"><span>일시</span><span>현상 / 조치 내용</span><span></span></div>` + state.rows.map((r, i) => `<div class="timeline-row"><input aria-label="일시" value="${esc(r[0])}" data-i="${i}" data-k="0"><input aria-label="현상 및 조치 내용" value="${esc(r[1])}" data-i="${i}" data-k="1"><button class="remove-row" type="button" data-remove="${i}" aria-label="행 삭제">×</button></div>`).join(''); }
function esc(v) { return String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])); }
renderRows();
$('timelineEditor').addEventListener('input', e => { if (e.target.dataset.i) state.rows[+e.target.dataset.i][+e.target.dataset.k] = e.target.value; });
$('timelineEditor').addEventListener('click', e => { if (e.target.dataset.remove !== undefined) { state.rows.splice(+e.target.dataset.remove, 1); renderRows(); } });
$('addRow').onclick = () => { state.rows.push(['15:00', '새로운 현상 또는 조치 내용을 입력하세요']); renderRows(); };
$('templateList').addEventListener('click', e => { const card = e.target.closest('.template-card'); if (!card) return; state.template = card.dataset.template; document.querySelectorAll('.template-card').forEach(c => c.classList.toggle('selected', c === card)); });
$('resetButton').onclick = () => { if (confirm('현재 내용을 초기화할까요?')) location.reload(); };

function data() { return { title: $('title').value, severity: $('severity').value, date: $('date').value, author: $('author').value, summary: $('summary').value, result: $('result').value, rows: state.rows }; }
function xe(v) { return String(v).replace(/[<>&'"]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c])); }
function download(blob, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
$('xmlButton').onclick = () => downloadXmlParts(buildIncident, `surrodocs-incident-${state.format}-parts.xml`);

// Minimal ZIP writer: DOCX is OOXML in a ZIP container. Stored entries keep this mockup dependency-free.
const enc = new TextEncoder();
function crc32(bytes) { let c = ~0; for (const b of bytes) { c ^= b; for (let k=0;k<8;k++) c = (c >>> 1) ^ (0xEDB88320 & -(c & 1)); } return ~c >>> 0; }
let LAST_PARTS = {};
function zip(files) { LAST_PARTS = files; let parts=[], central=[], offset=0; Object.entries(files).forEach(([name, content]) => { const n=enc.encode(name), d=typeof content==='string'?enc.encode(content):content, crc=crc32(d), head=new Uint8Array(30+n.length); const v=new DataView(head.buffer); v.setUint32(0,0x04034b50,true); v.setUint16(4,20,true); v.setUint32(14,crc,true); v.setUint32(18,d.length,true); v.setUint32(22,d.length,true); v.setUint16(26,n.length,true); head.set(n,30); parts.push(head,d); const c=new Uint8Array(46+n.length), cv=new DataView(c.buffer); cv.setUint32(0,0x02014b50,true); cv.setUint16(4,20,true); cv.setUint16(6,20,true); cv.setUint32(16,crc,true); cv.setUint32(20,d.length,true); cv.setUint32(24,d.length,true); cv.setUint16(28,n.length,true); cv.setUint32(42,offset,true); c.set(n,46); central.push(c); offset += head.length+d.length; }); const centralSize=central.reduce((a,x)=>a+x.length,0), end=new Uint8Array(22), ev=new DataView(end.buffer); ev.setUint32(0,0x06054b50,true); ev.setUint16(8,central.length,true); ev.setUint16(10,central.length,true); ev.setUint32(12,centralSize,true); ev.setUint32(16,offset,true); return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}); }
function wt(text, props='') { return `<w:r>${props}<w:t xml:space="preserve">${xe(text)}</w:t></w:r>`; }
function para(text, style='') { return `<w:p>${style?`<w:pPr><w:pStyle w:val="${style}"/></w:pPr>`:''}${wt(text)}</w:p>`; }
function tableXml(d, type) { const head=DOC_TEMPLATES[type].head; const rows=d.rows.map((r,i)=>`<w:tr>${i===0?`<w:tc><w:tcPr><w:shd w:fill="${head}"/><w:gridSpan w:val="1"/></w:tcPr>${para('일시')}</w:tc>`:''}<w:tc><w:tcPr>${i===0?`<w:shd w:fill="${head}"/>`:''}${i>0?'':'<w:gridSpan w:val="1"/>'}</w:tcPr>${para(i===0?'현상 / 조치 내용':r[1])}</w:tc>${i===0?'<w:tc><w:tcPr><w:shd w:fill="'+head+'"/></w:tcPr>'+para('')+'</w:tc>':''}</w:tr>`).join(''); const body=d.rows.map(r=>`<w:tr><w:tc>${para(r[0])}</w:tc><w:tc><w:tcPr><w:gridSpan w:val="2"/></w:tcPr>${para(r[1])}</w:tc></w:tr>`).join(''); return `<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D9E1E5"/><w:bottom w:val="single" w:sz="4" w:color="D9E1E5"/><w:insideH w:val="single" w:sz="4" w:color="E9EEF0"/></w:tblBorders></w:tblPr>${rows}${body}</w:tbl>`; }
function docx(d) { const tpl=DOC_TEMPLATES[state.template], accent=tpl.accent, title=tpl.kicker; const document=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${para(title,'Title')}${para(d.title,'Heading1')}${para(`발생일자  ${d.date}     작성자  ${d.author}     등급  ${d.severity}`)}${para('장애 내용','Heading2')}${para(d.summary)}${para('시간대별 장애 현상','Heading2')}${tableXml(d,state.template)}${para('조치 결과','Heading2')}${para(d.result)}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1100" w:right="1200" w:bottom="1100" w:left="1200"/></w:sectPr></w:body></w:document>`; const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="맑은 고딕"/><w:sz w:val="20"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="240"/></w:pPr><w:rPr><w:color w:val="${accent}"/><w:b/><w:sz w:val="18"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="Heading 2"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:before="240" w:after="100"/></w:pPr><w:rPr><w:color w:val="${accent}"/><w:b/></w:rPr></w:style></w:styles>`; return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/_rels/document.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>', 'word/document.xml':document,'word/styles.xml':styles}); }
function buildIncident() { return state.format === 'hwpx' ? hwpxIncident(data(), state.template) : docx(data()); }
$('docFormat').addEventListener('click', e => {
  const b = e.target.closest('button'); if (!b) return;
  state.format = b.dataset.fmt;
  document.querySelectorAll('#docFormat button').forEach(x => x.classList.toggle('selected', x === b));
  $('downloadButton').firstElementChild.textContent = state.format.toUpperCase() + ' 다운로드';
});
$('downloadButton').onclick = () => download(buildIncident(), `surrodocs-${state.template}-incident-report.${state.format}`);
$('mapButton').onclick = () => showMapping('incident', state.format, DOC_TEMPLATES[state.template]);
