import React, { useEffect, useMemo, useState } from 'react';
import { hasSearch, searchNodes } from '../utils/nodeSearch.js';
import NewCreation from './NewCreation.jsx';

const neutral = '#8b95a5';
const typeColor = (type) => ({ product_type: '#8b5e34', part: '#b45309', component: '#2563eb', concept: '#7c3aed', domain: '#0f766e', process: '#be123c', reference_material: '#0369a1', identifier: '#64748b', spec_code: '#475569', label: '#64748b', qualifier: '#64748b' }[type] || '#64748b');
const title = (node) => node?.name || node?.node_id || '항목 없음';
const visualNodeTypes = new Set(['product_type', 'part', 'component', 'concept', 'domain', 'process', 'reference_material']);
const relationName = (type) => ({ ALIAS_OF_ITEM: '대체어', BRIDGES_TO: '참조물질명', BROADER_THAN: '상위어', COMPOSED_OF: '구성 항목', HAS_COMPONENT: '구성품', HAS_DESCRIPTION: '설명', HAS_IDENTIFIER: '식별자', HAS_LABEL: '라벨', HAS_QUALIFIER: '한정자', HAS_SPEC_CODE: '규격코드', HAS_SURFACE_FORM: '표기형태', IN_DOMAIN: '도메인', MADE_OF: '물질 구성', NOT_CONFUSE_WITH: '혼동 방지 항목', SUBSTITUTABLE_BY: '대체 가능 항목', USED_IN_PROCESS: '공정명' }[type] || type);

export default function GraphCanvas({ data, filters, selected, setSelected, editMode, onContextMenu, onCanvasMenu, zoom, setZoom }) {
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [drag, setDrag] = useState(null);
  const [nodePositions, setNodePositions] = useState(() => { try { return JSON.parse(localStorage.getItem('entity-resolution-node-positions') || '{}'); } catch { return {}; } });
  const visible = useMemo(() => {
    let nodes = searchNodes(data, filters).filter((node) => visualNodeTypes.has(node.node_type));
    const partIds = data.nodes.filter((node) => node.node_type === 'part' && (!filters.productType || node.props?.product_type === filters.productType)).map((node) => node.node_id);
    const filterIds = [...new Set([...Object.values(filters.selectedByType || {}).filter(Boolean), ...(filters.productType ? partIds : [])])];
    const connectedNodes = (starts) => { const included = new Set(starts); let frontier = new Set(starts); for (let depth = 0; depth < 2; depth += 1) { const next = new Set(); data.edges.filter((edge) => frontier.has(edge.from) || frontier.has(edge.to)).forEach((edge) => { const other = frontier.has(edge.from) ? edge.to : edge.from; if (!included.has(other)) { included.add(other); next.add(other); } }); frontier = next; } return included; };
    if (filters.focusNode) return data.nodes.filter((node) => connectedNodes([filters.focusNode]).has(node.node_id) && visualNodeTypes.has(node.node_type)).slice(0, 55);
    if (filterIds.length) {
      const included = connectedNodes(filterIds); let frontier = new Set(data.nodes.filter((node) => filterIds.includes(node.node_id) && node.node_type === 'concept').map((node) => node.node_id));
      while (frontier.size) { const next = new Set(); data.edges.filter((edge) => edge.edge_type === 'BROADER_THAN' && frontier.has(edge.to)).forEach((edge) => { if (!included.has(edge.from)) { included.add(edge.from); next.add(edge.from); } }); frontier = next; }
      return data.nodes.filter((node) => included.has(node.node_id) && visualNodeTypes.has(node.node_type)).slice(0, 55);
    }
    if (filters.neighbors && !hasSearch(filters)) nodes = nodes.slice(0, 36);
    return nodes.slice(0, 55);
  }, [data, filters]);
  const ids = new Set(visible.map((node) => node.node_id));
  const edges = data.edges.filter((edge) => ids.has(edge.from) && ids.has(edge.to)).slice(0, 85);
  const related = useMemo(() => { if (!selected?.node_id) return new Set(); const output = new Set([selected.node_id]); edges.filter((edge) => edge.from === selected.node_id || edge.to === selected.node_id).forEach((edge) => output.add(edge.from === selected.node_id ? edge.to : edge.from)); return output; }, [edges, selected]);
  const positions = useMemo(() => { const groups = ['product_type', 'part', 'component', 'concept', 'domain', 'process', 'reference_material', 'other']; const grouped = Object.fromEntries(groups.map((group) => [group, []])); visible.forEach((node) => (grouped[node.node_type] || grouped.other).push(node)); const x = { product_type: 55, part: 250, component: 455, concept: 680, domain: 875, process: 875, reference_material: 1060, other: 350 }; const output = {}; groups.forEach((group) => grouped[group].forEach((node, index) => { output[node.node_id] = { x: x[group], y: 72 + index * 76 }; })); return output; }, [visible]);
  const nodeAt = (id) => nodePositions[id] || positions[id];
  const canvasHeight = Math.max(720, ...visible.map((node) => nodeAt(node.node_id).y + 100));
  useEffect(() => { localStorage.setItem('entity-resolution-node-positions', JSON.stringify(nodePositions)); }, [nodePositions]);
  const onMouseDown = (event) => { if (event.target.tagName !== 'svg' && event.target.dataset.canvas !== 'true') return; setDrag({ x: event.clientX - pan.x, y: event.clientY - pan.y }); };
  const onMouseMove = (event) => { if (!drag) return; if (drag.nodeId) { const rect = event.currentTarget.getBoundingClientRect(); setNodePositions((current) => ({ ...current, [drag.nodeId]: { x: Math.max(15, (event.clientX - rect.left) / zoom - 76), y: Math.max(15, (event.clientY - rect.top) / zoom - 24) } })); return; } setPan({ x: event.clientX - drag.x, y: event.clientY - drag.y }); };
  if (editMode === 'new') return <NewCreation data={data} />;
  return <div className="graph-shell" onClick={() => setSelected(null)} onContextMenu={onCanvasMenu}><div className="graph-toolbar"><span><b>{visible.length}</b> 항목 · <b>{edges.length}</b> 관계</span><div><button onClick={() => setZoom(Math.min(1.5, zoom + .1))}>＋</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom(Math.max(.5, zoom - .1))}>－</button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>맞춤</button></div></div><div className="graph-scroll"><svg className="graph" viewBox={`0 0 1180 ${canvasHeight}`} style={{ height: canvasHeight }} onMouseDown={onMouseDown} onMouseMove={onMouseMove} onMouseUp={() => setDrag(null)} onMouseLeave={() => setDrag(null)} data-canvas="true"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#a8b2c0" /></marker></defs><g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}><g className="edges">{edges.map((edge) => { const a = nodeAt(edge.from); const b = nodeAt(edge.to); const isRelated = Boolean(selected?.node_id) && (edge.from === selected.node_id || edge.to === selected.node_id); return <g key={edge.edge_id} onContextMenu={(event) => { event.stopPropagation(); onContextMenu(event, 'edge', edge); }}><path className={`edge ${selected?.edge_id === edge.edge_id ? 'selected' : ''} ${selected?.node_id && !isRelated ? 'muted' : ''} ${isRelated ? 'related' : ''}`} d={`M${a.x + 76},${a.y + 24} C${(a.x + b.x) / 2},${a.y + 24} ${(a.x + b.x) / 2},${b.y + 24} ${b.x},${b.y + 24}`} markerEnd="url(#arrow)" onClick={(event) => { event.stopPropagation(); setSelected(edge); }} /><text x={(a.x + b.x) / 2} y={(a.y + b.y) / 2 + 16}>{relationName(edge.edge_type)}</text></g>; })}</g><g className="nodes">{visible.map((node) => { const p = nodeAt(node.node_id); const active = selected?.node_id === node.node_id; const isRelated = related.has(node.node_id); return <g key={node.node_id} className={`node ${active ? 'selected' : ''} ${selected?.node_id && !isRelated ? 'muted' : ''} ${isRelated && !active ? 'related' : ''}`} transform={`translate(${p.x} ${p.y})`} onMouseDown={(event) => { event.stopPropagation(); setDrag({ nodeId: node.node_id }); }} onClick={(event) => { event.stopPropagation(); setSelected(node); }} onContextMenu={(event) => { event.stopPropagation(); onContextMenu(event, 'node', node); }}><rect width="152" height="49" rx="7" fill="#fff" stroke={neutral} /><rect width="5" height="49" rx="3" fill={neutral} /><text className="node-type" x="15" y="17" fill={typeColor(node.node_type)}>{node.node_type}</text><text className="node-name" x="15" y="36">{title(node).slice(0, 20)}</text></g>; })}</g></g></svg></div><div className="graph-help">항목 드래그: 위치 변경 · 빈 공간 드래그: 화면 이동 · {editMode ? '우클릭: 항목/관계 추가·수정·삭제' : '항목 클릭: 상세 정보 표시'}</div></div>;
}
