import React, { useMemo, useState } from 'react';

const textOf = (node) => `${node.node_id} ${node.name || ''} ${JSON.stringify(node.props || {})}`.toLowerCase();
const includesTerms = (text, value) => value.trim().toLowerCase().split(/\s+/).filter(Boolean).every((term) => text.includes(term));
function findCandidates(data, fields) {
  const query = fields.materialName.trim(); if (!query) return [];
  const byId = new Map(data.nodes.map((node) => [node.node_id, node]));
  const connected = (id) => { const seen = new Set([id]); let frontier = new Set([id]); for (let step = 0; step < 2; step += 1) { const next = new Set(); data.edges.filter((edge) => frontier.has(edge.from) || frontier.has(edge.to)).forEach((edge) => { const other = frontier.has(edge.from) ? edge.to : edge.from; if (!seen.has(other)) { seen.add(other); next.add(other); } }); frontier = next; } return [...seen].map((nodeId) => byId.get(nodeId)).filter(Boolean); };
  return data.nodes.filter((node) => node.node_type === 'concept' && includesTerms(textOf(node), query)).map((node) => { const nearby = connected(node.node_id); const context = nearby.map(textOf).join(' '); const exact = node.name.toLowerCase() === query.toLowerCase() || node.props?.abbreviations?.some((abbr) => abbr.toLowerCase() === query.toLowerCase()); const score = Math.min(100, (exact ? 100 : 82) + (!fields.part || nearby.some((candidate) => candidate.node_id === fields.part) ? 5 : 0) + (!fields.materialProcess.trim() || includesTerms(context, fields.materialProcess) ? 3 : 0)); const bridges = data.edges.filter((edge) => edge.from === node.node_id && edge.edge_type === 'BRIDGES_TO').map((edge) => ({ edge, reference: byId.get(edge.to) })); return { node, score, bridges }; }).sort((left, right) => right.score - left.score).slice(0, 10);
}

export default function MatchingTest({ data, onSelect }) {
  const [fields, setFields] = useState({ productType: '', part: '', description: '', materialName: '', materialProcess: '', notes: '' }); const [submitted, setSubmitted] = useState(false);
  const productTypes = [...new Set(data.nodes.filter((node) => node.node_type === 'part').map((node) => node.props?.product_type).filter(Boolean))]; const parts = data.nodes.filter((node) => node.node_type === 'part' && (!fields.productType || node.props?.product_type === fields.productType)); const candidates = useMemo(() => submitted ? findCandidates(data, fields) : [], [data, fields, submitted]); const set = (key, value) => { setFields((current) => ({ ...current, [key]: value, ...(key === 'productType' ? { part: '' } : {}) })); setSubmitted(false); };
  return <section className="matching-test"><div className="test-head"><span className="eyebrow">LCI REFERENCE MATCH TEST</span><h2>매칭결과 테스트</h2><p>입력된 제품·공정·물질 정보를 바탕으로 물질개념과 LCI 참조 DB 및 ref_id 후보를 확인합니다.</p></div><form className="matching-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="form-grid"><label>제품유형<select value={fields.productType} onChange={(event) => set('productType', event.target.value)}><option value="">전체</option>{productTypes.map((type) => <option key={type} value={type}>{type === 'automotive' ? '자동차 부품' : type}</option>)}</select></label><label>파트<select value={fields.part} onChange={(event) => set('part', event.target.value)}><option value="">전체</option>{parts.map((part) => <option key={part.node_id} value={part.node_id}>{part.name}</option>)}</select></label><label className="wide">전체설명<textarea value={fields.description} onChange={(event) => set('description', event.target.value)} placeholder="제품 또는 BOM 행의 전체 설명" /></label><label>투입물질명<input value={fields.materialName} onChange={(event) => set('materialName', event.target.value)} placeholder="예: PC, 폴리카보네이트" required /></label><label>투입물질 공정<input value={fields.materialProcess} onChange={(event) => set('materialProcess', event.target.value)} placeholder="예: 사출성형" /></label><label className="wide">기타 부가설명<textarea value={fields.notes} onChange={(event) => set('notes', event.target.value)} placeholder="등급, 농도, 규격, 공급사 정보 등" /></label></div><button className="match-submit" type="submit">LCI 참조 매칭</button></form>{submitted && <div className="match-results">{candidates.length ? candidates.map(({ node, score, bridges }) => <article key={node.node_id}><button className="concept-result" onClick={() => onSelect(node)}><div><b>{node.name}</b><span>{node.props?.english_name || node.props?.name_en || node.node_id}</span></div><strong>{score}%</strong></button><div className="bridge-results"><h3>매칭 참조 DB / ref_id</h3>{bridges.length ? bridges.map(({ edge, reference }) => <div key={edge.edge_id}><b>{reference?.name || edge.to}</b><span>{edge.props?.lci_db_name || '-'} · ref_id: {edge.props?.ref_id || '-'}</span><small>{edge.props?.match_type || '정확'} · {edge.props?.lci_mapping_priority || ''}</small>{edge.props?.mapping_kind === 'lci_proxy' && <small className="proxy-note">프록시: {edge.props?.proxy_reason} / {edge.props?.conservatism_direction}</small>}</div>) : <p>연결된 LCI 참조 DB가 없습니다.</p>}</div></article>) : <p className="no-results">매칭되는 물질개념이 없습니다.</p>}</div>}</section>;
}
