import React, { useState } from 'react';

export default function NewCreation({ data }) {
  const [form, setForm] = useState({ productType: 'automotive', partName: '', process: '', description: '', file: null });
  const [duplicate, setDuplicate] = useState(null);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const productTypes = data.nodes.filter((node) => node.node_type === 'product_type').map((node) => ({ value: node.props?.product_type || node.node_id.replace(/^PT:/, ''), name: node.name })).filter((item, index, list) => list.findIndex((other) => other.value === item.value) === index);
  const reset = () => setForm((current) => ({ ...current, partName: '', process: '', description: '', file: null }));
  const submit = (event) => { event.preventDefault(); const existing = data.nodes.find((node) => node.node_type === 'part' && node.props?.product_type === form.productType && node.name.trim().toLowerCase() === form.partName.trim().toLowerCase()); if (existing) return setDuplicate(existing); window.dispatchEvent(new CustomEvent('entity-create-part', { detail: { form, mode: 'new' } })); reset(); };
  const createDuplicate = (mode) => { window.dispatchEvent(new CustomEvent('entity-create-part', { detail: { form, mode, existingId: duplicate.node_id } })); setDuplicate(null); reset(); };
  const editExisting = () => { window.dispatchEvent(new CustomEvent('entity-edit-existing-part', { detail: duplicate })); setDuplicate(null); };
  const types = productTypes.length ? productTypes : [{ value: 'automotive', name: '자동차 부품' }];
  return <section className="new-creation"><div className="test-head"><span className="eyebrow">NEW PRODUCT CONTEXT</span><h2>신규 생성</h2><p>제품유형과 파트 정보를 등록하면 구성물질과 LCI 브리지를 연결할 수 있습니다.</p></div><form className="creation-form" onSubmit={submit}><label>제품유형<select value={form.productType} onChange={(event) => set('productType', event.target.value)}>{types.map((item) => <option key={item.value} value={item.value}>{item.name}</option>)}</select></label><label>파트<input value={form.partName} onChange={(event) => set('partName', event.target.value)} placeholder="예: R램프" required /></label><label>파트 공정<input value={form.process} onChange={(event) => set('process', event.target.value)} placeholder="예: 조립, 사출성형" /></label><label>전체 기술설명<textarea value={form.description} onChange={(event) => set('description', event.target.value)} placeholder="제품 기능, 구성, 소재 요구사항 등을 입력하세요." /></label><label>참조파일 (BOM, Excel 등)<input type="file" accept=".xlsx,.xls,.csv,.pdf,.doc,.docx" onChange={(event) => set('file', event.target.files?.[0] || null)} /><small>{form.file ? `${form.file.name} · ${(form.file.size / 1024).toFixed(1)} KB` : '파일 메타데이터가 신규 파트에 기록됩니다.'}</small></label><button className="match-submit" type="submit">신규 파트 생성</button></form>{duplicate && <div className="duplicate-dialog"><div><h3>동일한 파트가 있습니다</h3><p><b>{duplicate.name}</b>은(는) 이미 선택한 제품유형에 등록되어 있습니다.</p><button onClick={() => createDuplicate('sequence')}>순번을 붙여 신규 생성</button><button onClick={editExisting}>기존 항목 수정</button><button onClick={() => createDuplicate('replace')}>입력값으로 기존 파트 교체</button><button onClick={() => setDuplicate(null)}>취소</button></div></div>}</section>;
}
